//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApp.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Drinks
    {
        public int Order_Id { get; set; }
        public int Drink_Id { get; set; }
        public Nullable<int> Count_Of { get; set; }
    
        public virtual Drinks Drinks { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
